import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import {Layout} from "@/components/layout";
import {Suspense} from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props:{
  children: React.ReactNode,
  params: { locale: string }
}) {
  return (
    <html lang={props.params.locale}>
      <body className={inter.className}>
          <Layout>
              {props.children}
          </Layout>

      </body>
    </html>
  );
}
